DROP TABLE IF EXISTS data;

CREATE TABLE DATA(id SERIAL PRIMARY KEY, name VARCHAR(70),mob VARCHAR(20), loc VARCHAR(100), nature TEXT, budget VARCHAR(20), service VARCHAR(30), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_created_at ON DATA(created_at DESC);